name: google_maps
author: "Alexandre Ardhuin <alexandre.ardhuin@gmail.com>"
homepage: https://github.com/a14n/dart-google-maps
version: 1.1.2-dev
description: With that package you will be able to use Google Maps JavaScript API from Dart scripts.
dependencies:
  js: '>=0.0.15 <1.0.0'
  js_wrap:
    git: git://github.com/a14n/dart-js-wrap.git
  unittest: any
  meta: any
  browser: any

